### ISSUE TITLE
Strange behavior after update to 0.0.9

### ISSUE THREAD

**Issue by dukhevych** [joe-tom/outclick#2]
@joe-tom hey! Thnx for fixing the 1st issue, but looks like after that your plugin started conflicting with other events on the page. In any browser.

I use your 'outclick' with jQuery
I have such code:

`
$megamenu[0].addEventListener('outclick', function(e){
    if ($megamenu.hasClass('is-open')) {
        // close megamenu
    }
}, [$opener[0]]);

$opener.on('click', function(e){
  // open megamenu
});
`

$opener click is now triggered when clicking on any area of the page.

**Comment by joe-tom** [comment]
What version of jQuery are you using? I'll add this to the tests

**Comment by Landen13** [comment]
@joe-tom "jquery": "2.2.4"

**Comment by joe-tom** [comment]
I fixed it! It was a silly error.

**Comment by Landen13** [comment]
@joe-tom thanks! Now works as expected.
